language: node_js
node_js:
  - "10"
  - "node"
cache:
  directories:
    - "$HOME/.npm"
before_install:
  - npm install -g npm@latest
  - npm --version
install:
  - npm install -g codecov
  - npm ci
script:
  - npm test
  - codecov
